Repository 42PAW/42PAW, pull requests merged in 2023-11, with the labels that each got.

#151 Be/dev/feat tagging#146
  backend/src/main/java/proj/pet/comment/controller/CommentController.java
  backend/src/main/java/proj/pet/comment/service/CommentFacadeServiceImpl.java
  backend/src/main/java/proj/pet/mapper/MemberMapper.java
  backend/src/main/java/proj/pet/member/contorller/MemberController.java
  backend/src/main/java/proj/pet/member/dto/MemberNicknameValidateResponseDto.java
  backend/src/main/java/proj/pet/member/dto/MemberProfileResponseDto.java
  backend/src/main/java/proj/pet/member/service/MemberFacadeService.java
  backend/src/main/java/proj/pet/member/service/MemberFacadeServiceImpl.java
  backend/src/main/java/proj/pet/member/service/MemberQueryService.java
  backend/src/main/java/proj/pet/member/service/MemberQueryServiceImpl.java
  backend/src/main/java/proj/pet/member/service/MemberService.java
  backend/src/main/java/proj/pet/member/service/MemberServiceImpl.java
  backend/src/main/java/proj/pet/notice/repository/NoticeRepository.java
  backend/src/main/java/proj/pet/tag/service/TagEventPublisher.java
  backend/src/test/java/proj/pet/member/MemberControllerTest.java
  backend/src/test/java/proj/pet/notice/EventPublishTest.java
Labels: FE, BE, FEAT, TEST

#154 [FE] 댓글 유저 태그 기능 추가 #146
  frontend/src/api/axios/axios.custom.ts
  frontend/src/components/RightSection/CommentSection/CommentItem.tsx
  frontend/src/components/RightSection/CommentSection/CommentSection.tsx
  frontend/src/components/modals/ModalContainer.tsx
  frontend/src/components/modals/UserNotFoundModal/UserNotFoundModal.tsx
  frontend/src/pages/ImageUploader.tsx
  frontend/src/recoil/atom.ts
  frontend/src/types/enum/modal.enum.ts
  frontend/src/types/interface/modal.interface.ts
Labels: FE, BE, FEAT

#155 [FE] 댓글 유저 태그 기능 핫픽스 (닉네임 짤림, 다국어 지원, 모바일뷰 등) #146
  frontend/src/components/RightSection/CommentSection/CommentItem.tsx
  frontend/src/components/RightSection/CommentSection/CommentSection.tsx
  frontend/src/components/modals/UserNotFoundModal/UserNotFoundModal.tsx
  frontend/src/languages/en.ts
  frontend/src/languages/fr.ts
  frontend/src/languages/ger.ts
  frontend/src/languages/it.ts
  frontend/src/languages/jp.ts
  frontend/src/languages/ko.ts
  frontend/src/languages/pt.ts
  frontend/src/languages/spa.ts
Labels: FE, FIX

#158 [FE] FIX: 유저 태깅 핫픽스 #146
  frontend/src/api/axios/axios.custom.ts
  frontend/src/components/RightSection/CommentSection/CommentItem.tsx
  frontend/src/components/RightSection/CommentSection/CommentSection.tsx
Labels: FE, FIX

#159 [FE] FIX: 유저 태깅 핫픽스 to main #146
  frontend/src/api/axios/axios.custom.ts
  frontend/src/components/RightSection/CommentSection/CommentItem.tsx
  frontend/src/components/RightSection/CommentSection/CommentSection.tsx
Labels: FE, FIX
