Repository 42PAW/42PAW, pull requests merged in 2023-09, with the labels that each got.

#93 [FE] FIX, REFACT: 프로필 수정 모달 디자인 수정 및 데이터 가져오는 방식 변경
  frontend/src/components/modals/ProfileEditModal/ProfileEditModal.tsx
  frontend/src/pages/ProfilePage/Component/ProfileInfoComponent.tsx
  frontend/src/pages/ProfilePage/MyProfilePage.tsx
  frontend/src/recoil/atom.ts
  frontend/src/types/dto/member.dto.ts
  frontend/src/types/interface/profile.interface.ts
Labels: FE, FIX, REFACTOR

#95 [BE] 게시글과 댓글에서도 해당 사용자에 대해 팔로우 여부를 알도록 수정
  backend/src/main/java/proj/pet/board/dto/BoardInfoDto.java
  backend/src/main/java/proj/pet/board/service/BoardQueryServiceImpl.java
  backend/src/main/java/proj/pet/comment/controller/CommentController.java
  backend/src/main/java/proj/pet/comment/dto/CommentDto.java
  backend/src/main/java/proj/pet/comment/service/CommentFacadeService.java
  backend/src/main/java/proj/pet/comment/service/CommentFacadeServiceImpl.java
  backend/src/main/java/proj/pet/comment/service/CommentQueryService.java
  backend/src/main/java/proj/pet/comment/service/CommentQueryServiceImpl.java
  backend/src/main/java/proj/pet/mapper/BoardMapper.java
  backend/src/main/java/proj/pet/mapper/CommentMapper.java
  backend/src/test/java/proj/pet/board/service/BoardQueryServiceImplTest.java
  backend/src/test/java/proj/pet/comment/service/CommentQueryServiceTest.java
Labels: BE, FEAT, FIX

#102 [FE] FIX: heic파일 이미지 업로드 기능 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/modals/ProfileEditModal/ProfileEditModal.tsx
Labels: FE, FEAT, FIX

#105 [FE] FIX: 프로필 창에서 디자인 수정. 프로필 사진 비율 안깨지게 css조정
  frontend/src/api/axios/axios.custom.ts
  frontend/src/components/Board/BoardTemplate.tsx
  frontend/src/components/LeftMenuSection/LeftMenuDesktop.tsx
  frontend/src/components/LeftMenuSection/LeftMenuTablet.tsx
  frontend/src/components/modals/ProfileEditModal/ProfileEditModal.tsx
  frontend/src/pages/ProfilePage/Component/ProfileInfoComponent.tsx
Labels: FE, FIX

#113 [BE] FEAT : Controller에서 Body를 받는 부분들에 대해서 Validation 적용
  backend/src/main/java/proj/pet/block/controller/BlockController.java
  backend/src/main/java/proj/pet/block/dto/BlockRequestDto.java
  backend/src/main/java/proj/pet/board/controller/BoardController.java
  backend/src/main/java/proj/pet/board/dto/BoardCreateRequestDto.java
  backend/src/main/java/proj/pet/category/controller/CategoryController.java
  backend/src/main/java/proj/pet/category/dto/CategoryUpdateRequestDto.java
  backend/src/main/java/proj/pet/comment/controller/CommentController.java
  backend/src/main/java/proj/pet/comment/dto/CommentCreateRequestDto.java
  backend/src/main/java/proj/pet/comment/service/CommentFacadeService.java
  backend/src/main/java/proj/pet/comment/service/CommentFacadeServiceImpl.java
  backend/src/main/java/proj/pet/follow/controller/FollowController.java
  backend/src/main/java/proj/pet/follow/dto/FollowRequestDto.java
  backend/src/main/java/proj/pet/member/contorller/MemberController.java
  backend/src/main/java/proj/pet/member/dto/MemberCreateRequestDto.java
  backend/src/main/java/proj/pet/member/dto/MemberLanguageChangeRequestDto.java
  backend/src/main/java/proj/pet/member/dto/MemberProfileChangeRequestDto.java
  backend/src/main/java/proj/pet/reaction/controller/ReactionController.java
  backend/src/main/java/proj/pet/reaction/dto/ReactionRequestDto.java
  backend/src/main/java/proj/pet/report/controller/ReportController.java
  backend/src/main/java/proj/pet/report/dto/ReportRequestDto.java
  backend/src/main/java/proj/pet/scrap/controller/ScrapController.java
  backend/src/main/java/proj/pet/scrap/dto/ScrapCreateRequestDto.java
Labels: BE, FEAT

#114 [FE] FEAT: 건의사항 or 버그 제보 버튼 추가
  frontend/public/assets/reporting.png
  frontend/src/api/axios/axios.custom.ts
  frontend/src/components/SettingButton.tsx
  frontend/src/pages/ProfilePage/Component/ProfileInfoComponent.tsx
  frontend/src/pages/ProfilePage/Component/ProfileTemplate.tsx
  frontend/src/pages/ProfilePage/MyProfilePage.tsx
  frontend/src/pages/ProfilePage/ProfilePage.tsx
Labels: FE, FEAT, FIX

#115 [BE] FEAT: Controller에 AOP로 Logging 구현
  backend/src/main/java/proj/pet/utils/domain/ControllerLog.java
Labels: BE, FEAT

#116 [FE] FEAT: 언어번역 기능 완성
  frontend/src/api/axios/axios.custom.ts
  frontend/src/components/AnimalButtonContainer.tsx
  frontend/src/components/Board/BoardTemplate.tsx
  frontend/src/components/RightSection/AnimalFilterSection/AnimalFilterSection.tsx
  frontend/src/components/RightSection/BannedMemberSection/BannedMemberSection.tsx
  frontend/src/components/RightSection/CommentSection/CommentSection.tsx
  frontend/src/components/RightSection/FollowerSection/FollowerSection.tsx
  frontend/src/components/RightSection/FollowingSection/FollowingSection.tsx
  frontend/src/components/RightSection/SearchSection/SearchSection.tsx
  frontend/src/components/RightSection/SearchSection/test.json
  frontend/src/components/modals/BanModal/BanModal.tsx
  frontend/src/components/modals/DeleteModal/DeleteModal.tsx
  frontend/src/components/modals/LoginModal/LoginModal.tsx
  frontend/src/components/modals/MeatballModal.tsx
  frontend/src/components/modals/ProfileCardModal/ProfileCardModal.tsx
  frontend/src/components/modals/ProfileEditModal/ProfileEditModal.tsx
  frontend/src/components/modals/ReportModal/ReportModal.tsx
  frontend/src/hooks/useNicknameValidation.tsx
  frontend/src/languages/en.ts
  frontend/src/languages/fr.ts
  frontend/src/languages/ger.ts
  frontend/src/languages/it.ts
  frontend/src/languages/jp.ts
  frontend/src/languages/ko.ts
  frontend/src/languages/pt.ts
  frontend/src/languages/spa.ts
  frontend/src/pages/ImageUploader.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/MyProfileBoardsPage.tsx
  frontend/src/pages/ProfileBoardsPage.tsx
  frontend/src/pages/ProfilePage/Component/ProfileInfoComponent.tsx
  frontend/src/pages/SignUpPage/Sections/AnimalFilterSection.tsx
  frontend/src/pages/SignUpPage/Sections/IntroductionSection.tsx
  frontend/src/pages/SignUpPage/Sections/NicknameSection.tsx
  frontend/src/pages/SignUpPage/Sections/ProfileImageSection.tsx
  frontend/src/pages/SignUpPage/Sections/SuccessSection.tsx
  frontend/src/pages/SignUpPage/components/ProfileCard.tsx
Labels: FE, FEAT

#120 [FE] FIX: 언어 변경 hook 에러 수정
  frontend/package.json
  frontend/src/hooks/useNicknameValidation.tsx
Labels: FE, FIX

#122 [FE] FIX: SignUp 언어 설정 반영
  frontend/src/components/AnimalButtonContainer.tsx
  frontend/src/pages/SignUpPage/SignUpPage.tsx
Labels: FE, FIX

#123 [FE] FIX: 팔로우목록 통해서 타인 프로필 갔을 때 게시물 잘못 불러오는 문제 해결
  frontend/src/hooks/useNavigateCustom.tsx
  frontend/src/pages/ProfilePage/Component/FollowerItem.tsx
  frontend/src/pages/ProfilePage/Component/FollowingItem.tsx
  frontend/src/pages/ProfilePage/ProfilePage.tsx
Labels: FE, FIX

#126 [FE] FIX: react-query Cache -> 항상 stale
  frontend/src/hooks/useFetch.tsx
  frontend/src/hooks/useNavigateCustom.tsx
  frontend/src/main.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/MyProfileBoardsPage.tsx
  frontend/src/pages/ProfileBoardsPage.tsx
  frontend/src/pages/ProfilePage/MyProfilePage.tsx
  frontend/src/pages/ProfilePage/ProfilePage.tsx
  frontend/src/recoil/atom.ts
  frontend/src/types/enum/board.category.enum.ts
Labels: FE, FIX

#127 [BE] AnimalCategory 엔티티 삭제 및 의존성, 테스트 수정
  backend/database/paw_local.sql
  backend/src/main/java/proj/pet/board/service/BoardQueryServiceImpl.java
  backend/src/main/java/proj/pet/board/service/BoardServiceImpl.java
  backend/src/main/java/proj/pet/category/controller/CategoryController.java
  backend/src/main/java/proj/pet/category/domain/AnimalCategory.java
  backend/src/main/java/proj/pet/category/domain/BoardCategoryFilter.java
  backend/src/main/java/proj/pet/category/domain/MemberCategoryFilter.java
  backend/src/main/java/proj/pet/category/repository/AnimalCategoryRepository.java
  backend/src/main/java/proj/pet/category/repository/BoardCategoryFilterRepository.java
  backend/src/main/java/proj/pet/category/repository/MemberCategoryFilterRepository.java
  backend/src/main/java/proj/pet/category/service/AnimalCategoryService.java
  backend/src/main/java/proj/pet/category/service/CategoryFacadeService.java
  backend/src/main/java/proj/pet/category/service/CategoryFacadeServiceImpl.java
  backend/src/main/java/proj/pet/category/service/CategoryQueryServiceImpl.java
  backend/src/main/java/proj/pet/category/service/CategoryServiceImpl.java
  backend/src/main/java/proj/pet/member/service/MemberQueryServiceImpl.java
  backend/src/main/java/proj/pet/member/service/MemberServiceImpl.java
  backend/src/test/java/proj/pet/board/controller/BoardControllerTest.java
  backend/src/test/java/proj/pet/board/service/BoardServiceImplTest.java
  backend/src/test/java/proj/pet/category/controller/CategoryControllerTest.java
  backend/src/test/java/proj/pet/member/MemberControllerTest.java
  backend/src/test/java/proj/pet/testutil/testdouble/category/TestAnimalCategory.java
  backend/src/test/java/proj/pet/testutil/testdouble/category/TestBoardCategoryFilter.java
  backend/src/test/java/proj/pet/testutil/testdouble/category/TestMemberCategoryFilter.java
Labels: BE, FIX

#133 [FE] FIX: 이미지 업로드 방식 변경, 이미지 업로드 시 비활성화 해야 하는 부분 처리
  frontend/src/components/modals/ProfileEditModal/ProfileEditModal.tsx
  frontend/src/components/processImage.tsx
  frontend/src/pages/SignUpPage/Sections/ProfileImageSection.tsx
  frontend/src/pages/SignUpPage/SignUpPage.tsx
  frontend/src/pages/SignUpPage/components/ProfileCard.tsx
Labels: FE, FEAT, FIX

#132 [BE] FIX: nickname validation 추가 및 적용 확인
  backend/src/main/java/proj/pet/member/service/MemberQueryServiceImpl.java
  backend/src/main/java/proj/pet/member/service/MemberServiceImpl.java
  backend/src/main/java/proj/pet/member/validation/NicknameValidation.java
Labels: BE, FIX

#136 [FE]업로드 로직 정리
  frontend/src/pages/ImageUploader.tsx
Labels: FE, BUG

#137 Be/dev/refector board view/#128
  backend/src/main/java/proj/pet/board/controller/BoardControllerV2.java
  backend/src/main/java/proj/pet/board/dto/BoardInfoDto.java
  backend/src/main/java/proj/pet/board/dto/BoardReactionCountDto.java
  backend/src/main/java/proj/pet/board/dto/BoardViewMapDto.java
  backend/src/main/java/proj/pet/board/dto/BoardViewSubDto.java
  backend/src/main/java/proj/pet/board/repository/BoardRepository.java
  backend/src/main/java/proj/pet/board/repository/BoardViewRepository.java
  backend/src/main/java/proj/pet/board/repository/BoardViewRepositoryImpl.java
  backend/src/main/java/proj/pet/board/service/BoardFacadeService.java
  backend/src/main/java/proj/pet/board/service/BoardFacadeServiceImpl.java
  backend/src/main/java/proj/pet/board/service/BoardQueryService.java
  backend/src/main/java/proj/pet/board/service/BoardQueryServiceImpl.java
  backend/src/main/java/proj/pet/category/repository/BoardCategoryFilterRepository.java
  backend/src/main/java/proj/pet/mapper/BoardMapper.java
  backend/src/main/java/proj/pet/reaction/domain/Reaction.java
  backend/src/main/java/proj/pet/scrap/controller/ScrapControllerV2.java
  backend/src/main/java/proj/pet/scrap/service/ScrapFacadeService.java
  backend/src/main/java/proj/pet/scrap/service/ScrapFacadeServiceImpl.java
  backend/src/main/java/proj/pet/utils/log/ControllerLogAspect.java
  backend/src/main/java/proj/pet/utils/log/DomainLogAspect.java
  backend/src/main/java/proj/pet/utils/log/ServiceLogAspect.java
  backend/src/test/java/proj/pet/board/service/BoardQueryServiceImplTest.java
  backend/src/test/java/proj/pet/member/domain/MemberTest.java
Labels: BE, REFACTOR

#142 [BE] FIX: 리팩토링 테스트 결과 반영하여 수정
  backend/src/main/java/proj/pet/board/controller/BoardControllerV2.java
  backend/src/main/java/proj/pet/board/repository/BoardRepository.java
  backend/src/main/java/proj/pet/board/repository/BoardRepositoryCustomImpl.java
  backend/src/main/java/proj/pet/board/repository/BoardViewRepository.java
  backend/src/main/java/proj/pet/board/repository/BoardViewRepositoryImpl.java
  backend/src/main/java/proj/pet/board/service/BoardFacadeService.java
  backend/src/main/java/proj/pet/board/service/BoardFacadeServiceImpl.java
  backend/src/main/java/proj/pet/board/service/BoardQueryService.java
  backend/src/main/java/proj/pet/board/service/BoardQueryServiceImpl.java
  backend/src/main/java/proj/pet/scrap/controller/ScrapControllerV2.java
  backend/src/main/java/proj/pet/scrap/service/ScrapFacadeService.java
  backend/src/main/java/proj/pet/scrap/service/ScrapFacadeServiceImpl.java
Labels: BE, FIX, REFACTOR
