Repository 42PAW/42PAW, pull requests merged in 2023-08, with the labels that each got.

#15 [FE] FEAT: 토스트 컴포넌트 및 useToaster 훅 추가
  frontend/src/components/Board/BoardTemplate.tsx
  frontend/src/components/OptionButton.tsx
  frontend/src/components/modals/DeleteModal/DeleteModal.tsx
  frontend/src/components/modals/ModalLayout.tsx
  frontend/src/components/toast/Toaster.tsx
  frontend/src/hooks/useToaster.tsx
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/pages/Layout.tsx
  frontend/src/recoil/atom.ts
  frontend/src/types/interface/toast.interface.ts
Labels: FE, FEAT

#19 [BE] 추상 클래스로 Entity 단순화 및 불변식, 도메인 검증, 익셉션 핸들링 구현
  backend/src/main/java/proj/pet/block/domain/Block.java
  backend/src/main/java/proj/pet/board/domain/Board.java
  backend/src/main/java/proj/pet/board/domain/BoardMedia.java
  backend/src/main/java/proj/pet/category/domain/AnimalCategory.java
  backend/src/main/java/proj/pet/category/domain/BoardCategoryFilter.java
  backend/src/main/java/proj/pet/category/domain/MemberCategoryFilter.java
  backend/src/main/java/proj/pet/category/domain/Species.java
  backend/src/main/java/proj/pet/comment/domain/Comment.java
  backend/src/main/java/proj/pet/exception/ExceptionStatus.java
  backend/src/main/java/proj/pet/follow/domain/Follow.java
  backend/src/main/java/proj/pet/member/domain/Member.java
  backend/src/main/java/proj/pet/member/domain/OauthProfile.java
  backend/src/main/java/proj/pet/member/domain/OauthType.java
  backend/src/main/java/proj/pet/reaction/domain/Reaction.java
  backend/src/main/java/proj/pet/report/domain/Report.java
  backend/src/main/java/proj/pet/scrap/domain/Scrap.java
  backend/src/main/java/proj/pet/utils/domain/ConsumptionCompositeKey.java
  backend/src/main/java/proj/pet/utils/domain/IdDomain.java
  backend/src/main/java/proj/pet/utils/domain/MemberCompositeKey.java
  backend/src/main/java/proj/pet/utils/domain/RuntimeExceptionThrower.java
Labels: BE, FEAT

#22 [FE] REFACTOR: SignUpPage 퍼널 구조 리팩토링
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/backArrow.png
  frontend/src/components/AnimalButtonContainer.tsx
  frontend/src/pages/SignUpPage/Sections/AnimalFilterSection.tsx
  frontend/src/pages/SignUpPage/Sections/IntroductionSection.tsx
  frontend/src/pages/SignUpPage/Sections/NicknameSection.tsx
  frontend/src/pages/SignUpPage/Sections/ProfileImageSection.tsx
  frontend/src/pages/SignUpPage/Sections/SuccessSection.tsx
  frontend/src/pages/SignUpPage/SignUpPage.tsx
  frontend/src/pages/SignUpPage/components/ProfileCard.tsx
  frontend/src/pages/SignUpPage/components/RevertButton.tsx
Labels: FE, REFACTOR

#61 [FE] FEAT: 검색창 구현
  frontend/src/api/axios/axios.custom.ts
  frontend/src/components/RightSection/CommentSection/CommentSection.tsx
  frontend/src/components/RightSection/SearchSection/SearchBar.tsx
  frontend/src/components/RightSection/SearchSection/SearchItem.tsx
  frontend/src/components/RightSection/SearchSection/SearchSection.tsx
  frontend/src/hooks/useFetch.tsx
  frontend/src/recoil/atom.ts
  frontend/src/types/dto/member.dto.ts
Labels: FE, FEAT

#59 [BE] FEAT, FIX: IdDomain을 복합 키로도 관리할 수 있도록 확장
  backend/src/main/java/proj/pet/board/domain/Board.java
  backend/src/main/java/proj/pet/board/domain/BoardMedia.java
  backend/src/main/java/proj/pet/category/domain/AnimalCategory.java
  backend/src/main/java/proj/pet/category/domain/BoardCategoryFilter.java
  backend/src/main/java/proj/pet/category/domain/MemberCategoryFilter.java
  backend/src/main/java/proj/pet/comment/domain/Comment.java
  backend/src/main/java/proj/pet/follow/domain/Follow.java
  backend/src/main/java/proj/pet/member/domain/Member.java
  backend/src/main/java/proj/pet/reaction/domain/Reaction.java
  backend/src/main/java/proj/pet/report/domain/Report.java
  backend/src/main/java/proj/pet/scrap/domain/Scrap.java
  backend/src/main/java/proj/pet/utils/domain/IdDomain.java
  backend/src/main/java/proj/pet/utils/domain/IdentityDomain.java
Labels: BE, FEAT

#65 [FE] FEAT: 내프로필, 타인프로필 일부 분리. 내프로필에서 스크랩 가져오기.
  frontend/src/api/axios/axios.custom.ts
  frontend/src/components/modals/ProfileCardModal/ProfileCardModal.tsx
  frontend/src/components/profilePage/PhotoZoneComponent.tsx
  frontend/src/components/profilePage/ProfileInfoComponent.tsx
  frontend/src/hooks/useFetch.tsx
  frontend/src/hooks/useNavigateCustom.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/ProfilePage.tsx
  frontend/src/pages/ProfilePage/Component/PhotoZoneComponent.tsx
  frontend/src/pages/ProfilePage/Component/ProfileTemplate.tsx
  frontend/src/pages/ProfilePage/MyProfilePage.tsx
  frontend/src/pages/ProfilePage/ProfilePage.tsx
Labels: FE, FEAT

#67 [FE] FEAT: PWA manifest 및 serviceWorker 추가
  frontend/index.html
  frontend/public/icons/icon.png
  frontend/public/manifest.json
  frontend/serviceWorker.js
  frontend/src/pages/MainPage.tsx
  frontend/vite.config.ts
Labels: FE, FEAT

#68 Fe/dev/feat search/#62
  frontend/src/components/RightSection/SearchSection/SearchItem.tsx
  frontend/src/components/RightSection/SearchSection/SearchSection.tsx
  frontend/src/pages/ImageUploader.tsx
  frontend/src/pages/UploadPage.tsx
  frontend/src/recoil/atom.ts
  frontend/src/types/dto/member.dto.ts
Labels: FE, FEAT

#71 [FE] FEAT: 비로그인 상태 언어 설정 및 동물 카테고리 업데이트를 위한 localStorage 추가
  frontend/src/components/RightSection/AnimalFilterSection/AnimalFilterSection.tsx
  frontend/src/components/modals/LanguageModal/LanguageModal.tsx
  frontend/src/components/modals/LanguageModal/languageModalUtils.ts
  frontend/src/pages/Layout.tsx
Labels: FE, FEAT

#73 [BE] FEAT, TEST : Board쪽 간단한 유닛 && E2E 테스트 추가
  backend/src/main/java/proj/pet/board/controller/BoardController.java
  backend/src/main/java/proj/pet/board/domain/Board.java
  backend/src/main/java/proj/pet/board/domain/BoardMedia.java
  backend/src/main/java/proj/pet/board/repository/BoardRepositoryCustomImpl.java
  backend/src/main/java/proj/pet/board/service/.DS_Store
  backend/src/main/java/proj/pet/board/service/BoardQueryServiceImpl.java
  backend/src/main/java/proj/pet/board/service/BoardServiceImpl.java
  backend/src/main/java/proj/pet/category/domain/BoardCategoryFilter.java
  backend/src/main/java/proj/pet/exception/ExceptionStatus.java
  backend/src/test/java/category/domain/service/AnimalCategoryServiceTest.java
  backend/src/test/java/proj/pet/board/controller/BoardControllerTest.java
  backend/src/test/java/proj/pet/board/service/BoardQueryServiceImplTest.java
  backend/src/test/java/proj/pet/board/service/BoardQueryServiceTest.java
  backend/src/test/java/proj/pet/board/service/BoardServiceImplTest.java
  backend/src/test/java/proj/pet/board/service/BoardServiceTest.java
  backend/src/test/java/proj/pet/testutil/PersistHelper.java
  backend/src/test/java/proj/pet/testutil/testdouble/MockEntityStringifier.java
  backend/src/test/java/proj/pet/testutil/testdouble/board/TestBoard.java
  backend/src/test/java/proj/pet/testutil/testdouble/board/TestBoardMedia.java
  backend/src/test/java/proj/pet/testutil/testdouble/member/TestMember.java
Labels: BE, FEAT, TEST

#78 [BE] FIX, FEAT: Board 이미지 비어있는 경우 에러처리 및 멤버 프로필 이미지 비어있을 때 null로 생성
  backend/src/main/java/proj/pet/board/controller/BoardController.java
  backend/src/main/java/proj/pet/board/domain/BoardMedia.java
  backend/src/main/java/proj/pet/board/dto/BoardCreateRequestDto.java
  backend/src/main/java/proj/pet/member/contorller/MemberController.java
  backend/src/main/java/proj/pet/member/service/MemberServiceImpl.java
  backend/src/test/java/proj/pet/board/controller/BoardControllerTest.java
  backend/src/test/java/proj/pet/member/MemberControllerTest.java
Labels: BE, FEAT, FIX, TEST

#85 feat: [FE] FIX: 프로필화면 백그라운드 이미지 url 경로 변경
  frontend/public/assets/Intersect.svg
  frontend/src/assets/Intersect.png
  frontend/src/pages/ProfilePage/Component/ProfileInfoComponent.tsx
Labels: FE, FIX
